export const READY_TO_PLAY_CONFIGURATION_VERSION = "4";
export const AURORA_READY_TO_PLAY_FILTER_PATH =
  "Aurora/User/Scripts/Content/Filters/XboxCompanionReady.lua";
export const READY_TO_PLAY_MARKER_PATH =
  `.xbox-downloader/ready-to-play-v${READY_TO_PLAY_CONFIGURATION_VERSION}.marker`;
// Gravado pelo console, nao pela preparacao: registra que o hook ja pediu um Aurora.Restart()
// para este cadastro. Enquanto ele existir, um cadastro que se repete nao reinicia de novo.
export const READY_TO_PLAY_RESTART_GUARD_PATH =
  `.xbox-downloader/ready-to-play-v${READY_TO_PLAY_CONFIGURATION_VERSION}.restart`;

export function generateReadyToPlayLaunchIni(): string {
  return [
    "[Paths]",
    "Default = Usb:\\Aurora\\default.xex",
    // Sem Dumpfile o DashLaunch despeja a excecao apenas na UART e o usuario so ve o
    // banner "Fatal Crash Intercepted!", sem nenhum vestigio para diagnosticar.
    "Dumpfile = Usb:\\crashlog.txt",
    "",
    "[Settings]",
    "noupdater = true",
    "liveblock = true",
    "livestrong = false",
    "",
  ].join("\r\n");
}

export function generateReadyToPlayMarker(): string {
  return `xbox-companion-ready-to-play-v${READY_TO_PLAY_CONFIGURATION_VERSION}\r\n`;
}

export function generateAuroraReadyToPlayFilterLua(): string {
  return [
    "-- Xbox 360 Companion: configuracao automatica para conectar e jogar.",
    "-- Este arquivo e carregado automaticamente pelo Aurora como Content Filter.",
    'scriptPermissions = { "filesystem", "sql" }',
    "",
    `local MARKER_PATH = ".xbox-downloader\\\\ready-to-play-v${READY_TO_PLAY_CONFIGURATION_VERSION}.marker"`,
    `local RESTART_GUARD_PATH = ".xbox-downloader\\\\ready-to-play-v${READY_TO_PLAY_CONFIGURATION_VERSION}.restart"`,
    "local READY_TO_PLAY_PATHS = {",
    '    { path = "\\\\games", depth = 6 },',
    '    { path = "\\\\Content\\\\0000000000000000", depth = 5 }',
    "}",
    "",
    "local function sqlEscape(value)",
    '    return string.gsub(tostring(value or ""), "\'", "\'\'")',
    "end",
    "",
    "local function driveRoot(mountPoint)",
    '    local root = tostring(mountPoint or "")',
    '    if root ~= "" and string.sub(root, -1) ~= "\\\\" then',
    '        root = root .. "\\\\"',
    "    end",
    "    return root",
    "end",
    "",
    "local function normalizedSerial(value)",
    '    local serial = tostring(value or "")',
    '    if string.sub(serial, 1, 1) == "_" then serial = string.sub(serial, 2) end',
    "    return string.lower(serial)",
    "end",
    "",
    "local function findCompanionDrive()",
    "    local drives = FileSystem.GetDrives(false) or {}",
    '    local runningSerial = ""',
    "    for _, drive in ipairs(drives) do",
    '        local mountPoint = string.lower(tostring(drive["MountPoint"] or ""))',
    '        if string.sub(mountPoint, 1, 5) == "game:" then',
    '            runningSerial = normalizedSerial(drive["Serial"])',
    "            break",
    "        end",
    "    end",
    "",
    "    local candidates = {}",
    "    for _, drive in ipairs(drives) do",
    '        local root = driveRoot(drive["MountPoint"])',
    '        local serial = tostring(drive["Serial"] or "")',
    '        local marker = root .. MARKER_PATH',
    '        if root ~= "" and serial ~= "" and',
    '           FileSystem.FileExists(root .. "Aurora\\\\default.xex") and',
    "           FileSystem.FileExists(marker) then",
    "            if runningSerial ~= \"\" and normalizedSerial(serial) == runningSerial then",
    "                return root, serial",
    "            end",
    "            table.insert(candidates, { root = root, serial = serial })",
    "        end",
    "    end",
    "",
    "    if #candidates == 1 then return candidates[1].root, candidates[1].serial end",
    '    return "", ""',
    "end",
    "",
    "local function sqlSucceeded(result)",
    "    return result == true or tonumber(result) == 1",
    "end",
    "",
    "local function rowValue(row, upperName, lowerName)",
    "    return row[upperName] or row[lowerName]",
    "end",
    "",
    "local function insertScanPath(scanPath, deviceId, depth)",
    "    local escapedPath = sqlEscape(scanPath)",
    "    local escapedDeviceId = sqlEscape(deviceId)",
    "    local queries = {",
    '        "INSERT INTO scanpaths (path, deviceid, depth, scriptdata, optionsflags) VALUES (\'" .. escapedPath .. "\', \'" .. escapedDeviceId .. "\', " .. tostring(depth) .. ", \'\', 1);",',
    '        "INSERT INTO scanpaths (path, deviceid, depth, scriptdata) VALUES (\'" .. escapedPath .. "\', \'" .. escapedDeviceId .. "\', " .. tostring(depth) .. ", \'\');",',
    '        "INSERT INTO scanpaths (path, deviceid, depth) VALUES (\'" .. escapedPath .. "\', \'" .. escapedDeviceId .. "\', " .. tostring(depth) .. ");"',
    "    }",
    "    for _, query in ipairs(queries) do",
    "        if sqlSucceeded(Sql.Execute(query)) then return true end",
    "    end",
    "    return false",
    "end",
    "",
    "local function ensureScanPath(scanPath, deviceId, depth)",
    '    local rows = Sql.ExecuteFetchRows("SELECT id, path, deviceid, depth FROM scanpaths ORDER BY id ASC") or {}',
    "    for _, row in pairs(rows) do",
    '        local rowPath = tostring(rowValue(row, "Path", "path") or "")',
    '        local rowDeviceId = tostring(rowValue(row, "DeviceId", "deviceid") or "")',
    "        if string.lower(rowPath) == string.lower(scanPath) and",
    "           normalizedSerial(rowDeviceId) == normalizedSerial(deviceId) then",
    '            if tonumber(rowValue(row, "Depth", "depth")) ~= depth then',
    '                local id = tonumber(rowValue(row, "Id", "id"))',
    "                if id ~= nil then",
    '                    return sqlSucceeded(Sql.Execute("UPDATE scanpaths SET depth=" .. tostring(depth) .. " WHERE id=" .. tostring(id) .. ";"))',
    "                end",
    "            end",
    "            return false",
    "        end",
    "    end",
    "    return insertScanPath(scanPath, deviceId, depth)",
    "end",
    "",
    "local function configureReadyToPlay()",
    "    if FileSystem == nil or Sql == nil then",
    '        print("Xbox 360 Companion: APIs do Aurora ainda indisponiveis.")',
    "        return",
    "    end",
    "",
    "    local root, deviceId = findCompanionDrive()",
    '    if deviceId == "" then',
    '        print("Xbox 360 Companion: pendrive preparado nao identificado com seguranca.")',
    "        return",
    "    end",
    "",
    "    local guardPath = root .. RESTART_GUARD_PATH",
    "    local changed = false",
    "    for _, scanPath in ipairs(READY_TO_PLAY_PATHS) do",
    "        if ensureScanPath(scanPath.path, deviceId, scanPath.depth) then changed = true end",
    "    end",
    "",
    "    if not changed then",
    "        -- O banco ja tem os caminhos, entao o reinicio anterior valeu. Apagar a marca",
    "        -- devolve o direito a um reinicio se o Aurora recriar o banco depois.",
    "        if FileSystem.FileExists(guardPath) then FileSystem.DeleteFile(guardPath) end",
    '        print("Xbox 360 Companion: pronto para conectar e jogar.")',
    "        return",
    "    end",
    "",
    "    if FileSystem.FileExists(guardPath) then",
    "        -- Ja reiniciamos uma vez por este mesmo cadastro e ele nao sobreviveu ao boot.",
    "        -- Reiniciar de novo repetiria isso a cada boot: e o laco que o usuario ve como",
    "        -- console reiniciando sozinho logo ao inserir o pendrive.",
    '        print("Xbox 360 Companion: caminhos recadastrados sem reiniciar; abra Content > Scan Paths se os jogos nao aparecerem.")',
    "        return",
    "    end",
    "",
    "    -- A marca vai para o mesmo dispositivo que guarda o banco do Aurora. Se ela nao ficar",
    "    -- gravada, o cadastro tambem nao fica, e reiniciar so produziria o laco.",
    '    FileSystem.WriteFile(guardPath, deviceId .. "\\r\\n")',
    "    if not FileSystem.FileExists(guardPath) then",
    '        print("Xbox 360 Companion: sem a marca de reinicio no pendrive; nao vou reiniciar o Aurora.")',
    "        return",
    "    end",
    "",
    '    print("Xbox 360 Companion: caminhos configurados; reiniciando Aurora.")',
    "    if Aurora ~= nil and Aurora.Restart ~= nil then Aurora.Restart() end",
    "end",
    "",
    "local readyToPlayOk, readyToPlayError = pcall(configureReadyToPlay)",
    "if not readyToPlayOk then",
    '    print("Xbox 360 Companion: falha ao configurar jogos: " .. tostring(readyToPlayError))',
    "end",
    "",
  ].join("\r\n");
}
